### ISSUE TITLE
Missing requirement - HTML code of the search results page

### ISSUE THREAD

**Issue by olivierobert** [pkordel/multisearch#18]
Each search results must also have the HTML cache of the search result page taken at that time:

![image](https://user-images.githubusercontent.com/696529/96826933-a7d27100-145e-11eb-8ba0-36ec42e9071a.png)

This serves as an audit material for us to verify. In terms of product (it was a real one), it would allow users to track changes.

![image](https://user-images.githubusercontent.com/696529/96827303-7dcd7e80-145f-11eb-8f21-3dcfd4ec4bcd.png)

**Comment by pkordel** [comment]
@olivierobert the source html for each results page is currently stored in the `search_results` table in the column `html`. Did I understand the requirement correctly?

**Comment by olivierobert** [comment]
I miss that part indeed 🤦 

https://github.com/pkordel/multisearch/blob/69d95b52581c40d1a4b4946fe397b24763eea630/app/services/search_result/create.rb#L55

I am so accustomed to seeing it's actually rendered as well on the search results page as well by other candidates that I take it for granter. But as an improvement, showing it to the user along with the report would be good in terms of UX. Since the data is stored then it's good to make use of it.
